LOCAL_PATH := $(call my-dir)
POCO_INCLUDE_PATH := $(LOCAL_PATH)/poco/include
OPEN_SSL_INCLUDE_PATH := $(LOCAL_PATH)/openssl/include

include $(CLEAR_VARS)
LOCAL_MODULE := crypto
LOCAL_SRC_FILES := openssl/libs/$(TARGET_ARCH_ABI)/libcrypto.so
LOCAL_EXPORT_C_INCLUDES := OPEN_SSL_INCLUDE_PATH
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := ssl
LOCAL_SRC_FILES := openssl/libs/$(TARGET_ARCH_ABI)/libssl.so
LOCAL_EXPORT_C_INCLUDES := OPEN_SSL_INCLUDE_PATH
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoFoundation
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoFoundation.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoCrypto
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoCrypto.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_STATIC_LIBRARIES:= PocoFoundation
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoData
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoData.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_STATIC_LIBRARIES:= PocoFoundation
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoDataSQLite
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoDataSQLite.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_STATIC_LIBRARIES:= PocoFoundation
LOCAL_STATIC_LIBRARIES:= PocoData
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoJSON
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoJSON.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_STATIC_LIBRARIES:= PocoFoundation
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoNet
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoNet.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_STATIC_LIBRARIES:= PocoFoundation
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := PocoNetSSL
LOCAL_SRC_FILES := poco/libs/$(TARGET_ARCH_ABI)/libPocoNetSSL.a
LOCAL_EXPORT_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_STATIC_LIBRARIES := PocoFoundation
LOCAL_STATIC_LIBRARIES += PocoNet
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := __ModuleName__
LOCAL_SRC_FILES := $(shell (ruby $(LOCAL_PATH)/src_files_android_mk.rb __ModuleName__))
LOCAL_C_INCLUDES := $(POCO_INCLUDE_PATH)
LOCAL_LDLIBS := -llog
LOCAL_SHARED_LIBRARIES := crypto ssl
LOCAL_STATIC_LIBRARIES := PocoCrypto PocoNetSSL PocoNet PocoUtil PocoJSON PocoFoundation
include $(BUILD_SHARED_LIBRARY)